//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.25 at 05:34:12 PM IST 
//


package com.telefonica.pwdweb.wsdlimported;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for operationResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="operationResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="remainingPasswordAttempts" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="currentPasswordExpirationDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "operationResponse", propOrder = {
    "code",
    "description",
    "remainingPasswordAttempts",
    "currentPasswordExpirationDate"
})
public class OperationResponse {

    protected int code;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String remainingPasswordAttempts;
    @XmlElement(required = true)
    protected String currentPasswordExpirationDate;

    /**
     * Gets the value of the code property.
     * 
     */
    public int getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     */
    public void setCode(int value) {
        this.code = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the remainingPasswordAttempts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemainingPasswordAttempts() {
        return remainingPasswordAttempts;
    }

    /**
     * Sets the value of the remainingPasswordAttempts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemainingPasswordAttempts(String value) {
        this.remainingPasswordAttempts = value;
    }

    /**
     * Gets the value of the currentPasswordExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentPasswordExpirationDate() {
        return currentPasswordExpirationDate;
    }

    /**
     * Sets the value of the currentPasswordExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentPasswordExpirationDate(String value) {
        this.currentPasswordExpirationDate = value;
    }

}
