//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.27 at 03:34:18 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://telefonica.com/pwd.mgmt.webservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.telefonica.pwdweb.wsdlimported;
